version: 1

handlers:
    console:
        level: DEBUG
        format: >-
            <green>{time:YYYY-MM-DD HH:mm:ss}</green> |
            <level>{level}</level> |
            <cyan>{name}</cyan>:<cyan>{module}</cyan>:
            <cyan>{function}</cyan>:<cyan>{line}</cyan> -
            <level>{message}</level>

    file:
        sink: ../log/app.log
        level: INFO
        rotation: 2 MB
        format: >-
            {time:YYYY-MM-DD HH:mm:ss} |
            {level} |
            {module}:{function}:{line} - {message}

DB:
    path: ../db/CustomerInfo.db
